apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bot 
  janus-idp.io/tekton: bot
  backstage.io/kubernetes-id: bot
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: bot
resources: 
- application-dev.yaml