apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: bot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/chbot:319705ed7e02703a716368d03580d4b440e6c638@sha256:84ea79efe3479ddbf469a1be2ed6e2d4d6d2fdccc7f3890d9c14451db435a412 # use pre-built to bootstrap 
          name: app-inference
